#!/usr/bin/env python3
"""
Converts frontend files (HTML, CSS, JS) into gzip-compressed C byte arrays.
Generates embedded_files.h for inclusion in the ESP32 firmware.

Usage: python3 embed_frontend.py <frontend_dir> <output_header>
"""

import gzip
import os
import sys
import re


def sanitize_name(filename):
    """Convert filename to a valid C identifier."""
    name = os.path.basename(filename)
    name = re.sub(r'[^a-zA-Z0-9]', '_', name)
    return name


def compress_file(filepath):
    """Read and gzip-compress a file."""
    with open(filepath, 'rb') as f:
        data = f.read()
    return gzip.compress(data, compresslevel=9)


def generate_c_array(varname, data):
    """Generate a C byte array declaration."""
    lines = []
    lines.append(f'static const uint8_t {varname}_gz[] = {{')

    # Format as rows of 16 bytes
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        hex_vals = ', '.join(f'0x{b:02x}' for b in chunk)
        lines.append(f'    {hex_vals},')

    lines.append('};')
    lines.append(f'static const size_t {varname}_gz_len = sizeof({varname}_gz);')
    return '\n'.join(lines)


def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <frontend_dir> <output_header>")
        sys.exit(1)

    frontend_dir = sys.argv[1]
    output_path = sys.argv[2]

    if not os.path.isdir(frontend_dir):
        print(f"Error: {frontend_dir} is not a directory")
        sys.exit(1)

    # Files to embed
    extensions = {'.html', '.css', '.js'}
    files = []

    for fname in sorted(os.listdir(frontend_dir)):
        _, ext = os.path.splitext(fname)
        if ext in extensions:
            files.append(os.path.join(frontend_dir, fname))

    if not files:
        print("Warning: No frontend files found")

    # Generate header
    header_lines = [
        '#pragma once',
        '',
        '/* Auto-generated by embed_frontend.py - DO NOT EDIT */',
        '',
        '#include <stdint.h>',
        '#include <stddef.h>',
        '',
    ]

    for filepath in files:
        varname = sanitize_name(filepath)
        compressed = compress_file(filepath)
        original_size = os.path.getsize(filepath)

        print(f"  {os.path.basename(filepath)}: {original_size} -> {len(compressed)} bytes "
              f"({100 * len(compressed) / original_size:.0f}%)")

        header_lines.append(f'/* {os.path.basename(filepath)} ({original_size} bytes, '
                          f'gzip: {len(compressed)} bytes) */')
        header_lines.append(generate_c_array(varname, compressed))
        header_lines.append('')

    # Write output
    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
    with open(output_path, 'w') as f:
        f.write('\n'.join(header_lines))

    print(f"Generated {output_path} with {len(files)} embedded files")


if __name__ == '__main__':
    main()
